'use client';

/**
 * Comprehensive NBM product catalog for the workstation UI.
 * Organized into 7 operational categories mirroring AWIPS II / Pivotal Weather.
 *
 * Each product maps to a backend element code, colormap, and supported sub-selectors.
 */

export type ProductType = 'deterministic' | 'mean' | 'probabilistic';
export type Accumulation = '1h' | '6h' | '12h' | '24h' | '48h' | '72h';
export type Percentile = 10 | 25 | 50 | 75 | 90 | 95;

export type CategoryId =
  | 'temp_moisture'
  | 'precip_qpf'
  | 'winter'
  | 'wind'
  | 'convective'
  | 'aviation_marine'
  | 'fire';

export interface NBMProductDef {
  id: string;
  element: string; // backend element key
  label: string;
  shortLabel: string;
  description: string;
  category: CategoryId;
  colormap: string; // key into COLOUR_MAPS
  units: {
    native: string;
    imperial: string;
    metric: string;
  };
  types: ProductType[];
  defaultType: ProductType;
  accumulations?: Accumulation[];
  defaultAccum?: Accumulation;
  percentiles?: Percentile[];
  defaultPercentile?: Percentile;
  thresholds?: string[]; // display labels like "≥ 0.10\""
  thresholdValues?: number[]; // native values mm or m/s or degC
  searchable: string[]; // keywords for fuzzy search
  isFavoriteDefault?: boolean;
  versionNote?: string; // e.g., "NBM v4.2"
}

export interface CategoryDef {
  id: CategoryId;
  label: string;
  icon: string;
  description: string;
  products: NBMProductDef[];
}

export const CATEGORIES: CategoryDef[] = [
  {
    id: 'temp_moisture',
    label: 'Temperature & Moisture',
    icon: '🌡️',
    description: '2m temperature, dewpoint, RH, apparent temp',
    products: [
      {
        id: 'tmp',
        element: 'tmp',
        label: '2m Temperature',
        shortLabel: 'Temp',
        description: 'Temperature at 2 meters above ground',
        category: 'temp_moisture',
        colormap: 'nbm_temp',
        units: { native: '°C', imperial: '°F', metric: '°C' },
        types: ['deterministic', 'mean'],
        defaultType: 'deterministic',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        searchable: ['temperature', 'tmp', '2m', 'surface'],
        isFavoriteDefault: true,
      },
      {
        id: 'maxt',
        element: 'maxt',
        label: 'Max Temperature (12z-06z)',
        shortLabel: 'MaxT',
        description: 'Maximum temperature 12z-06z period',
        category: 'temp_moisture',
        colormap: 'nbm_temp',
        units: { native: '°C', imperial: '°F', metric: '°C' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        percentiles: [10, 25, 50, 75, 90, 95],
        defaultPercentile: 50,
        thresholds: ['≥ 0°F', '≥ 32°F', '≥ 70°F', '≥ 90°F', '≥ 100°F'],
        thresholdValues: [-17.8, 0, 21.1, 32.2, 37.8],
        searchable: ['max', 'maxt', 'high', 'temperature'],
      },
      {
        id: 'mint',
        element: 'mint',
        label: 'Min Temperature (00z-18z)',
        shortLabel: 'MinT',
        description: 'Minimum temperature 00z-18z period',
        category: 'temp_moisture',
        colormap: 'nbm_temp',
        units: { native: '°C', imperial: '°F', metric: '°C' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        thresholds: ['≤ 32°F', '≤ 20°F', '≤ 0°F', '≤ -20°F'],
        thresholdValues: [0, -6.7, -17.8, -28.9],
        searchable: ['min', 'mint', 'low', 'temperature', 'freeze'],
      },
      {
        id: 'dpt',
        element: 'tdp',
        label: 'Dewpoint Temperature',
        shortLabel: 'DewPt',
        description: 'Dewpoint at 2m',
        category: 'temp_moisture',
        colormap: 'nbm_temp',
        units: { native: '°C', imperial: '°F', metric: '°C' },
        types: ['deterministic', 'mean'],
        defaultType: 'deterministic',
        searchable: ['dewpoint', 'dpt', 'tdp', 'moisture', 'dew'],
      },
      {
        id: 'appt',
        element: 'appt',
        label: 'Apparent Temperature',
        shortLabel: 'AppT',
        description: 'Wind chill / heat index derived',
        category: 'temp_moisture',
        colormap: 'nbm_temp',
        units: { native: '°C', imperial: '°F', metric: '°C' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['apparent', 'feels like', 'wind chill', 'heat index'],
      },
      {
        id: 'rh',
        element: 'rh',
        label: 'Relative Humidity',
        shortLabel: 'RH',
        description: 'Relative humidity at 2m',
        category: 'temp_moisture',
        colormap: 'nbm_rh',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['deterministic', 'mean'],
        defaultType: 'deterministic',
        searchable: ['rh', 'humidity', 'relative'],
      },
      {
        id: 'maxrh',
        element: 'maxrh',
        label: 'Max Relative Humidity',
        shortLabel: 'MaxRH',
        description: 'Maximum RH in period',
        category: 'temp_moisture',
        colormap: 'nbm_rh',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['max rh', 'humidity'],
      },
      {
        id: 'minrh',
        element: 'minrh',
        label: 'Min Relative Humidity',
        shortLabel: 'MinRH',
        description: 'Minimum RH in period',
        category: 'temp_moisture',
        colormap: 'nbm_rh',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['min rh', 'humidity'],
      },
    ],
  },
  {
    id: 'precip_qpf',
    label: 'Precipitation & QPF',
    icon: '🌧️',
    description: 'Quantitative precipitation forecast, PoP, QMD',
    products: [
      {
        id: 'qpf01',
        element: 'qpf01',
        label: 'QPF 1-Hour',
        shortLabel: 'QPF 1h',
        description: '1-hour quantitative precipitation forecast',
        category: 'precip_qpf',
        colormap: 'nbm_precip',
        units: { native: 'mm', imperial: 'in', metric: 'mm' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        accumulations: ['1h'],
        defaultAccum: '1h',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        thresholds: ['≥ 0.01"', '≥ 0.10"', '≥ 0.25"', '≥ 0.50"', '≥ 1.00"'],
        thresholdValues: [0.254, 2.54, 6.35, 12.7, 25.4],
        searchable: ['qpf', 'precip', 'rain', '1h', 'hourly'],
        isFavoriteDefault: true,
      },
      {
        id: 'qpf06',
        element: 'qpf06',
        label: 'QPF 6-Hour',
        shortLabel: 'QPF 6h',
        description: '6-hour quantitative precipitation forecast',
        category: 'precip_qpf',
        colormap: 'nbm_precip',
        units: { native: 'mm', imperial: 'in', metric: 'mm' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        accumulations: ['6h'],
        defaultAccum: '6h',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        thresholds: ['≥ 0.10"', '≥ 0.25"', '≥ 0.50"', '≥ 1.00"', '≥ 2.00"'],
        thresholdValues: [2.54, 6.35, 12.7, 25.4, 50.8],
        searchable: ['qpf', 'precip', 'rain', '6h'],
        isFavoriteDefault: true,
      },
      {
        id: 'qpf12',
        element: 'qpf12',
        label: 'QPF 12-Hour',
        shortLabel: 'QPF 12h',
        description: '12-hour quantitative precipitation forecast',
        category: 'precip_qpf',
        colormap: 'nbm_precip',
        units: { native: 'mm', imperial: 'in', metric: 'mm' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        accumulations: ['12h'],
        defaultAccum: '12h',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        thresholds: ['≥ 0.10"', '≥ 0.50"', '≥ 1.00"', '≥ 2.00"', '≥ 3.00"'],
        thresholdValues: [2.54, 12.7, 25.4, 50.8, 76.2],
        searchable: ['qpf', 'precip', '12h'],
      },
      {
        id: 'qpf24',
        element: 'qpf24',
        label: 'QPF 24-Hour',
        shortLabel: 'QPF 24h',
        description: '24-hour quantitative precipitation forecast',
        category: 'precip_qpf',
        colormap: 'nbm_precip',
        units: { native: 'mm', imperial: 'in', metric: 'mm' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        accumulations: ['24h'],
        defaultAccum: '24h',
        percentiles: [10, 25, 50, 75, 90, 95],
        defaultPercentile: 50,
        thresholds: ['≥ 0.50"', '≥ 1.00"', '≥ 2.00"', '≥ 3.00"', '≥ 5.00"'],
        thresholdValues: [12.7, 25.4, 50.8, 76.2, 127],
        searchable: ['qpf', 'precip', '24h', 'daily'],
      },
      {
        id: 'pop06',
        element: 'pop06',
        label: 'PoP 6-Hour',
        shortLabel: 'PoP 6h',
        description: 'Probability of precipitation 6-hour',
        category: 'precip_qpf',
        colormap: 'nbm_pop',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['deterministic', 'probabilistic'],
        defaultType: 'probabilistic',
        accumulations: ['6h'],
        defaultAccum: '6h',
        searchable: ['pop', 'probability', 'precip', '6h'],
      },
      {
        id: 'pop12',
        element: 'pop12',
        label: 'PoP 12-Hour',
        shortLabel: 'PoP 12h',
        description: 'Probability of precipitation 12-hour',
        category: 'precip_qpf',
        colormap: 'nbm_pop',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['deterministic', 'probabilistic'],
        defaultType: 'probabilistic',
        accumulations: ['12h'],
        defaultAccum: '12h',
        searchable: ['pop', 'probability', '12h'],
        isFavoriteDefault: true,
      },
      {
        id: 'qmd_qpf06',
        element: 'qmd_qpf06',
        label: 'QMD QPF 6-Hour (Calibrated)',
        shortLabel: 'QMD 6h',
        description: 'Calibrated 6-hour QPF (QMD)',
        category: 'precip_qpf',
        colormap: 'nbm_precip',
        units: { native: 'mm', imperial: 'in', metric: 'mm' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        accumulations: ['6h'],
        defaultAccum: '6h',
        searchable: ['qmd', 'calibrated', 'qpf', '6h'],
      },
      {
        id: 'qmd_qpf24',
        element: 'qmd_qpf24',
        label: 'QMD QPF 24-Hour',
        shortLabel: 'QMD 24h',
        description: 'Calibrated 24-hour QPF',
        category: 'precip_qpf',
        colormap: 'nbm_precip',
        units: { native: 'mm', imperial: 'in', metric: 'mm' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        accumulations: ['24h'],
        defaultAccum: '24h',
        searchable: ['qmd', 'calibrated', '24h'],
      },
    ],
  },
  {
    id: 'winter',
    label: 'Winter Weather',
    icon: '❄️',
    description: 'Snow, ice, snow level, snow cover',
    products: [
      {
        id: 'snow',
        element: 'snow',
        label: 'Snowfall Accumulation',
        shortLabel: 'Snow',
        description: 'Total snow accumulation water equivalent',
        category: 'winter',
        colormap: 'nbm_precip',
        units: { native: 'mm', imperial: 'in', metric: 'mm' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        accumulations: ['6h', '12h', '24h', '48h', '72h'],
        defaultAccum: '24h',
        percentiles: [10, 25, 50, 75, 90, 95],
        defaultPercentile: 50,
        thresholds: ['≥ 1"', '≥ 3"', '≥ 6"', '≥ 12"', '≥ 18"'],
        thresholdValues: [25.4, 76.2, 152.4, 304.8, 457.2],
        searchable: ['snow', 'snowfall', 'winter', 'accumulation'],
        isFavoriteDefault: true,
        versionNote: 'NBM v4.2',
      },
      {
        id: 'snowc',
        element: 'snowc',
        label: 'Snow Cover',
        shortLabel: 'SnowCov',
        description: 'Snow cover extent',
        category: 'winter',
        colormap: 'nbm_pop',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['snow cover', 'snowc'],
      },
      {
        id: 'snowlev',
        element: 'snowlev',
        label: 'Snow Level',
        shortLabel: 'SnowLvl',
        description: 'Altitude of freezing level for snow',
        category: 'winter',
        colormap: 'nbm_temp',
        units: { native: 'm', imperial: 'ft', metric: 'm' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['snow level', 'freezing level', 'snowlev'],
      },
      {
        id: 'ice_accum',
        element: 'snow',
        label: 'Ice Accumulation (Freezing Rain)',
        shortLabel: 'Ice',
        description: 'Freezing rain ice accumulation proxy',
        category: 'winter',
        colormap: 'nbm_precip',
        units: { native: 'mm', imperial: 'in', metric: 'mm' },
        types: ['probabilistic'],
        defaultType: 'probabilistic',
        thresholds: ['≥ 0.01"', '≥ 0.10"', '≥ 0.25"'],
        thresholdValues: [0.254, 2.54, 6.35],
        searchable: ['ice', 'freezing rain', 'ice accumulation'],
      },
    ],
  },
  {
    id: 'wind',
    label: 'Wind & Wind Gusts',
    icon: '💨',
    description: 'Sustained wind, gusts, direction, probabilities',
    products: [
      {
        id: 'wind',
        element: 'wind',
        label: '10m Wind Speed',
        shortLabel: 'Wind',
        description: '10-meter sustained wind speed',
        category: 'wind',
        colormap: 'nbm_wind',
        units: { native: 'm/s', imperial: 'mph', metric: 'km/h' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        thresholds: ['≥ 20 mph', '≥ 30 mph', '≥ 40 mph', '≥ 50 mph'],
        thresholdValues: [8.94, 13.41, 17.88, 22.35],
        searchable: ['wind', 'speed', '10m', 'sustained'],
        isFavoriteDefault: true,
      },
      {
        id: 'gust',
        element: 'gust',
        label: 'Wind Gust',
        shortLabel: 'Gust',
        description: '10-meter wind gust speed',
        category: 'wind',
        colormap: 'nbm_wind',
        units: { native: 'm/s', imperial: 'mph', metric: 'km/h' },
        types: ['deterministic', 'mean', 'probabilistic'],
        defaultType: 'deterministic',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        thresholds: ['≥ 25 mph', '≥ 35 mph', '≥ 45 mph', '≥ 58 mph'],
        thresholdValues: [11.18, 15.65, 20.12, 25.93],
        searchable: ['gust', 'wind gust', 'gusts'],
        isFavoriteDefault: true,
      },
      {
        id: 'winddir',
        element: 'winddir',
        label: 'Wind Direction',
        shortLabel: 'WDir',
        description: '10-meter wind direction',
        category: 'wind',
        colormap: 'nbm_wind',
        units: { native: 'deg', imperial: 'deg', metric: 'deg' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['wind direction', 'wdir', 'direction'],
      },
      {
        id: 'probwind',
        element: 'probwind',
        label: 'Prob Wind ≥ Threshold',
        shortLabel: 'ProbWind',
        description: 'Probability wind exceeds threshold',
        category: 'wind',
        colormap: 'nbm_pop',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['probabilistic'],
        defaultType: 'probabilistic',
        thresholds: ['≥ 20kt', '≥ 25kt', '≥ 34kt', '≥ 40kt'],
        thresholdValues: [10.3, 13.4, 17.5, 20.6],
        searchable: ['prob wind', 'probability wind'],
      },
      {
        id: 'probgust',
        element: 'probgust',
        label: 'Prob Gust ≥ Threshold',
        shortLabel: 'ProbGust',
        description: 'Probability gust exceeds threshold',
        category: 'wind',
        colormap: 'nbm_pop',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['probabilistic'],
        defaultType: 'probabilistic',
        thresholds: ['≥ 25kt', '≥ 35kt', '≥ 50kt'],
        thresholdValues: [13.4, 17.5, 25.7],
        searchable: ['prob gust', 'probability gust'],
      },
    ],
  },
  {
    id: 'convective',
    label: 'Convective & Severe',
    icon: '⛈️',
    description: 'CAPE, reflectivity, severe weather parameters',
    products: [
      {
        id: 'sbcape',
        element: 'sbcape',
        label: 'Surface-Based CAPE',
        shortLabel: 'SBCAPE',
        description: 'Surface-based convective available potential energy',
        category: 'convective',
        colormap: 'nbm_precip',
        units: { native: 'J/kg', imperial: 'J/kg', metric: 'J/kg' },
        types: ['deterministic', 'mean'],
        defaultType: 'deterministic',
        thresholds: ['≥ 500 J/kg', '≥ 1000 J/kg', '≥ 2000 J/kg', '≥ 3000 J/kg'],
        thresholdValues: [500, 1000, 2000, 3000],
        searchable: ['cape', 'sbcape', 'convective', 'instability', 'severe'],
        isFavoriteDefault: false,
      },
      {
        id: 'refc',
        element: 'refc',
        label: 'Composite Reflectivity',
        shortLabel: 'RefC',
        description: 'Model composite reflectivity',
        category: 'convective',
        colormap: 'nbm_wind',
        units: { native: 'dBZ', imperial: 'dBZ', metric: 'dBZ' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['reflectivity', 'refc', 'radar', 'composite'],
      },
      {
        id: 'lightning',
        element: 'pop12',
        label: 'Lightning Probability',
        shortLabel: 'Lightning',
        description: 'Probability of lightning / thunderstorm',
        category: 'convective',
        colormap: 'nbm_pop',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['probabilistic'],
        defaultType: 'probabilistic',
        searchable: ['lightning', 'thunder', 'tstm', 'convective'],
      },
    ],
  },
  {
    id: 'aviation_marine',
    label: 'Aviation & Marine',
    icon: '✈️',
    description: 'Ceiling, visibility, sky, pressure, oceanic',
    products: [
      {
        id: 'ceil',
        element: 'ceil',
        label: 'Ceiling Height',
        shortLabel: 'Ceil',
        description: 'Ceiling height AGL',
        category: 'aviation_marine',
        colormap: 'nbm_temp',
        units: { native: 'm', imperial: 'ft', metric: 'm' },
        types: ['deterministic', 'probabilistic'],
        defaultType: 'deterministic',
        thresholds: ['< 1000ft', '< 3000ft', '< 5000ft'],
        thresholdValues: [304.8, 914.4, 1524],
        searchable: ['ceiling', 'ceil', 'aviation', 'cig', 'cloud'],
      },
      {
        id: 'vis',
        element: 'vis',
        label: 'Surface Visibility',
        shortLabel: 'Vis',
        description: 'Surface visibility',
        category: 'aviation_marine',
        colormap: 'nbm_pop',
        units: { native: 'm', imperial: 'mi', metric: 'km' },
        types: ['deterministic', 'probabilistic'],
        defaultType: 'deterministic',
        thresholds: ['< 1mi', '< 3mi', '< 5mi'],
        thresholdValues: [1609, 4828, 8046],
        searchable: ['visibility', 'vis', 'aviation', 'fog'],
      },
      {
        id: 'sky',
        element: 'sky',
        label: 'Total Sky Cover',
        shortLabel: 'Sky',
        description: 'Total sky cover percentage',
        category: 'aviation_marine',
        colormap: 'nbm_pop',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['deterministic', 'mean'],
        defaultType: 'deterministic',
        searchable: ['sky', 'cloud cover', 'clouds'],
      },
      {
        id: 'mslp',
        element: 'mslp',
        label: 'Mean Sea Level Pressure',
        shortLabel: 'MSLP',
        description: 'Mean sea level pressure',
        category: 'aviation_marine',
        colormap: 'nbm_temp',
        units: { native: 'Pa', imperial: 'inHg', metric: 'hPa' },
        types: ['deterministic', 'mean'],
        defaultType: 'deterministic',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        searchable: ['mslp', 'pressure', 'sea level'],
      },
      {
        id: 'pmslp',
        element: 'pmslp',
        label: 'MSLP Percentiles (Oceanic)',
        shortLabel: 'pMSLP',
        description: 'MSLP percentiles for oceanic domain',
        category: 'aviation_marine',
        colormap: 'nbm_temp',
        units: { native: 'Pa', imperial: 'inHg', metric: 'hPa' },
        types: ['probabilistic'],
        defaultType: 'probabilistic',
        percentiles: [10, 25, 50, 75, 90],
        defaultPercentile: 50,
        searchable: ['pmslp', 'oceanic', 'pressure percentile'],
      },
    ],
  },
  {
    id: 'fire',
    label: 'Fire Weather',
    icon: '🔥',
    description: 'RH, wind, gusts, temperature for fire weather',
    products: [
      {
        id: 'fire_rh',
        element: 'minrh',
        label: 'Min RH (Fire Weather)',
        shortLabel: 'MinRH Fire',
        description: 'Minimum relative humidity for fire weather assessment',
        category: 'fire',
        colormap: 'nbm_rh',
        units: { native: '%', imperial: '%', metric: '%' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        thresholds: ['≤ 15%', '≤ 25%', '≤ 35%'],
        thresholdValues: [15, 25, 35],
        searchable: ['fire', 'rh', 'humidity', 'min rh'],
      },
      {
        id: 'fire_wind',
        element: 'wind',
        label: 'Wind Speed (Fire Weather)',
        shortLabel: 'Fire Wind',
        description: 'Sustained wind for fire weather',
        category: 'fire',
        colormap: 'nbm_wind',
        units: { native: 'm/s', imperial: 'mph', metric: 'km/h' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['fire', 'wind', 'fire weather'],
      },
      {
        id: 'fire_gust',
        element: 'gust',
        label: 'Wind Gust (Fire Weather)',
        shortLabel: 'Fire Gust',
        description: 'Wind gust for fire weather / red flag',
        category: 'fire',
        colormap: 'nbm_wind',
        units: { native: 'm/s', imperial: 'mph', metric: 'km/h' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['fire', 'gust', 'red flag'],
      },
      {
        id: 'fire_tmp',
        element: 'maxt',
        label: 'Max Temp (Fire Weather)',
        shortLabel: 'Fire MaxT',
        description: 'Max temperature for fire weather',
        category: 'fire',
        colormap: 'nbm_temp',
        units: { native: '°C', imperial: '°F', metric: '°C' },
        types: ['deterministic'],
        defaultType: 'deterministic',
        searchable: ['fire', 'temperature', 'max'],
      },
    ],
  },
];

// ── Helpers ─────────────────────────────────────────────────────────────────
export function allProducts(): NBMProductDef[] {
  return CATEGORIES.flatMap(c => c.products);
}

export function getProductById(id: string): NBMProductDef | undefined {
  return allProducts().find(p => p.id === id);
}

export function getProductByElement(element: string): NBMProductDef | undefined {
  return allProducts().find(p => p.element === element);
}

export function searchProducts(query: string): NBMProductDef[] {
  if (!query.trim()) return allProducts();
  const q = query.toLowerCase().trim();
  // fuzzy: split into tokens, all tokens must be present in searchable or label
  const tokens = q.split(/\s+/);
  return allProducts().filter(p => {
    const haystack = [
      p.label.toLowerCase(),
      p.shortLabel.toLowerCase(),
      p.description.toLowerCase(),
      p.element.toLowerCase(),
      p.id.toLowerCase(),
      ...p.searchable.map(s => s.toLowerCase()),
    ].join(' ');
    return tokens.every(tok => haystack.includes(tok));
  });
}

export function getCategoryById(id: CategoryId): CategoryDef | undefined {
  return CATEGORIES.find(c => c.id === id);
}
